name: docker

on:
  workflow_dispatch:

env:
  IMAGE_NAME: RECAP
  CONTEXT: "./"
  NAMESPACE: nciccbr
  VERSION_TAG: 0.1.0

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare build-time variables
        id: vars
        run: |
          echo "DATE=$(date +"%Y-%m-%d")" >> "$GITHUB_OUTPUT"

      - name: debug
        run: |
          echo "the github tag is ${{ github.ref_name }}"
          echo "github event_name is ${{ github.event_name }}"
          echo "the version tag is ${{ env.VERSION_TAG }}"

      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.VERSION_TAG }}
          context: ${{ env.CONTEXT }}
          file: ${{ env.CONTEXT }}/Dockerfile
          build-args: |
            BUILD_DATE=${{ steps.vars.outputs.DATE }}
            BUILD_TAG=${{ steps.vars.outputs.VERSION_TAG }}
            REPONAME=${{ env.IMAGE_NAME }}
